cmake_minimum_required(VERSION 4.0)
project(prueba2 C)

set(CMAKE_C_STANDARD 11)

add_executable(prueba2 strings-ficheros/string.c)
add_executable(memoryAddress memoria/ma.c)
add_executable(maaR memoria/maaR.c)
add_executable(funciones funciones/funciones.c)
add_executable(recursion funciones/recursion.c)
add_executable(recursion2 funciones/recursion2.c)
add_executable(files strings-ficheros/files.c)
add_executable(estructuras estructuras/estructuras.c)
add_executable(estructurasCascada estructuras/estructurasCascada.c)
add_executable(punterosEnStructs estructuras/punterosEnStructs.c)
add_executable(union estructuras/union.c)
add_executable(typedef estructuras/typedef.c)
add_executable(structPadding estructuras/structPadding.c)
add_executable(enum estructuras/enum.c)
add_executable(pArith memoria/pArith.c)
add_executable(pierPoint memoria/pierPoint.c)
add_executable(inlineFunc funciones/inlineFunc.c)
add_executable(punterosEnFunciones funciones/punterosEnFunciones.c)
add_executable(callback funciones/callback.c)
add_executable(callbackQsort funciones/callbackQsort.c)
add_executable(allocate memoria/allocate.c)
